name: ExampleTemplate
renderJS: false
maxThreads: 1
version: 1

pipelines:
  - name: example
    url: http://example.com/
    selector: "body > div"
    next:
      - name: example__title
        selector: 'h1'
        attribute: '$text'
        transform: res.toLowerCase()

      - name: example__link
        selector: 'a'
        attribute: 'href'

      - pipe::2ndex

  - name: 2ndex
    url: 0@example__link
    wait: [pipe::example__link]
    selector: 'a img[alt="Homepage"]'
    attribute: 'src'
